### ISSUE TITLE
Updates in ur_description break ur5_demo_support

### ISSUE THREAD

**Issue by jettan** [ros-industrial-consortium/roscon_2015#2]
Due to various renaming conventions and updates in the ur_description package, plan_and_run/demo_setup.launch reports various errors in that it is not able to find several dae/stl and xacro files.

Diff patch follows below:

[patch.zip](https://github.com/ros-industrial-consortium/roscon_2015/files/131064/patch.zip)

**Comment by gavanderhoorn** [comment]
Thanks, but would it be possible to just push your changes to a branch on [your private fork](https://github.com/jettan/roscon_2015) of this repository and then open a PR? That would make reviewing these changes much, much easier.
